### ISSUE TITLE
Saving Step Changes

### ISSUE THREAD

**Issue by vickiriddio** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#135]
Hi,

I have been implementing these SPC charts into our dashboard but I am encountering an issue when I set the split limits on click, save the changes I have made and then I click off the page, when I come back the chart has reset itself back to the original form.

Is there a way that I can save the step changes that I have fixed so that it can be published into live in this form?

Thanks 

Vicki

**Comment by andrjohns** [comment]
Thanks so much for reporting this, I had no idea it was happening! 

I've just pushed a fix, can you try the development version and let me know if it all works for you?

You can access the dev version by downloading the `.pbiviz` file here: https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/releases/tag/latest

**Comment by vickiriddio** [comment]
Thank you for getting back to me so quickly and pushing this through.

When I have downloaded the visual it removes the chart and I am no longer able to see the visual.

**Comment by andrjohns** [comment]
Can you try removing the data from the chart and re-adding it?

**Comment by vickiriddio** [comment]
Still the same issue. 

It seems to happen when I download the update and even when I dont make any changes to the visual and come back to the report the chart disappears. 

I have tried to create the visual again with completely different data but it still does not show

**Comment by andrjohns** [comment]
Hmm, let me investigate and try to reproduce locally. I'll comment here once I've tracked it down and pushed a fix

**Comment by andrjohns** [comment]
Sorry about that, the latest development version should all be working now!

**Comment by vickiriddio** [comment]
Thank you so much for this.

Please could I check are we talking about version PBISPC.1.3.3.1.pbiviz?

As this encounters the same issue as yesterday. Vicki

**Comment by andrjohns** [comment]
Apologies for this taking multiple iterations! I've found and fixed another source of a visual crash, can you try the latest dev version again (should be 1.3.3.3 now)?

**Comment by vickiriddio** [comment]
Hi, 

thank you so much that works just as I would have expected. 

I appreciate you dealing with this as quickly as you did.

**Comment by andrjohns** [comment]
Great to hear, thanks!
